backend:
  name: github
  repo: yangbanpro/yangbanpro.github.io
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "📁 Blog 포스팅"
    folder: "_posts"
    filter:
      field: "category"
      value: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "default"}
      - {label: "카테고리", name: "category", widget: "hidden", default: "blog"}
      - {label: "제목", name: "title", widget: "string"}
      - {label: "대표 사진 (URL 또는 경로)", name: "image", widget: "image", required: false}
      - {label: "작성일자", name: "date", widget: "datetime"}
      - {label: "본문 내용 (마크다운/수식)", name: "body", widget: "markdown"}

  - name: "studies"
    label: "📁 Studies 기록"
    folder: "_posts"
    filter:
      field: "category"
      value: "studies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "default"}
      - {label: "카테고리", name: "category", widget: "hidden", default: "studies"}
      - {label: "제목", name: "title", widget: "string"}
      - {label: "대표 사진", name: "image", widget: "image", required: false}
      - {label: "작성일자", name: "date", widget: "datetime"}
      - {label: "본문 내용", name: "body", widget: "markdown"}

  - name: "paper-reviews"
    label: "📁 Paper Reviews 논문 리뷰"
    folder: "_posts"
    filter:
      field: "category"
      value: "paper-reviews"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "default"}
      - {label: "카테고리", name: "category", widget: "hidden", default: "paper-reviews"}
      - {label: "제목", name: "title", widget: "string"}
      - {label: "대표 사진", name: "image", widget: "image", required: false}
      - {label: "작성일자", name: "date", widget: "datetime"}
      - {label: "본문 내용", name: "body", widget: "markdown"}

  - name: "projects"
    label: "📁 Projects 설계 및 제작"
    folder: "_posts"
    filter:
      field: "category"
      value: "projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "default"}
      - {label: "카테고리", name: "category", widget: "hidden", default: "projects"}
      - {label: "제목", name: "title", widget: "string"}
      - {label: "대표 사진", name: "image", widget: "image", required: false}
      - {label: "작성일자", name: "date", widget: "datetime"}
      - {label: "본문 내용", name: "body", widget: "markdown"}
